version: "3.9"

services:
  llama:
    name: llama
    image: ghcr.io/ggml-org/llama.cpp:full-cuda
    ports:
      - "9931:9931"
    volumes:
      - /opt/models:/models
    devices:
      - nvidia.com/gpu=all
    security_opt: label=disable
    environment:
      - LLAMA_ARG_CTX_SIZE=131072
      - LLAMA_ARG_MODEL=/models/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf
      - LLAMA_ARG_ALIAS="Qwen3.6-35B"
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=9931
      - LLAMA_ARG_THREADS=8
      - LLAMA_ARG_N_PREDICT=512
      - LLAMA_ARG_ENDPOINT_METRICS=true
      - LLAMA_ARG_CACHE_TYPE_K=q8_0
      - LLAMA_ARG_CACHE_TYPE_V=q8_0
      - LLAMA_ARG_N_GPU_LAYERS=999
      - LLAMA_ARG_N_CPU_MOE=35
      - LLAMA_ARG_LOAD_MODE=mmap+mlock
    entrypoint: [ "/app/llama-server" ]
